FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --user -r requirements.txt
ENV PATH=/root/.local/bin:$PATH
EXPOSE 8000
ENTRYPOINT ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]