syntax = "proto3";

option csharp_namespace = "WorkflowService.Protos";

package WorkflowPlanSvc;

service WorkflowPlanSvc {
    rpc CreatePlan (CreateWorkflowPlanModel) returns (CreateWorkflowPlanResponse);
    rpc GetPlanByTaskId (GetPlanByTaskIdModel) returns (WorkflowPlanModel);
}

message CreateWorkflowPlanModel {
    string userId = 1;
    string taskId = 2;
    string plan = 3;
}

message CreateWorkflowPlanResponse {
    string id = 1;
}

message WorkflowPlanModel {
    string id = 1;
    string taskId = 2;
    string plan = 3;
}

message GetPlanByTaskIdModel {
    string userId = 1;
    string taskId = 2;
}