syntax = "proto3";

import "google/protobuf/timestamp.proto";
option csharp_namespace = "SchedulerService.Protos";

package ScheduleSvc;

service ScheduleSvc {
    rpc CreateSchedule (CreateScheduleModel) returns (CreateScheduleResponse);
    rpc EditSchedule (EditScheduleModel) returns (EditScheduleResponse);
    rpc DeleteSchedule (DeleteScheduleModel) returns (DeleteScheduleResponse);
}

message CreateScheduleModel {
    string userId = 1;
    string taskId = 2;
    string cronEx = 3;
    string timezone = 4;
}

message CreateScheduleResponse {
    string id = 1;
    google.protobuf.Timestamp nextRunAt = 2;
}

enum ScheduleStatus {
    ACTIVE = 0;
    PAUSED = 1;
}

message EditScheduleModel {
    string id = 1;
    string userId = 2;
    ScheduleStatus status = 3;
    string cronEx = 4;
}

message EditScheduleResponse {
    string id = 1;
    ScheduleStatus status = 2;
    string cronEx = 3;
    string timezone = 4;
    google.protobuf.Timestamp nextRunAt = 5;
}

message DeleteScheduleModel {
    string id = 1;
    string userId = 2;
}

message DeleteScheduleResponse {
    bool success = 1;
}