syntax = "proto3";

import "google/protobuf/timestamp.proto";
option csharp_namespace = "WorkflowService.Protos";

package WorkflowPlanSvc;

service WorkflowPlanSvc {
    rpc SavePlan (CreateWorkflowPlanModel) returns (CreateWorkflowPlanResponse);
    rpc GetPlanByTaskId (GetPlanByTaskIdModel) returns (WorkflowPlanModel);
}

message CreateWorkflowPlanModel {
    string userId = 1;
    string taskId = 2;
    string graph = 3;
}

message CreateWorkflowPlanResponse {
    string id = 1;
}

message WorkflowPlanModel {
    string id = 1;
    string taskId = 2;
    string graph = 3;
    google.protobuf.Timestamp createdAt = 4;
    google.protobuf.Timestamp updatedAt = 5;
}

message GetPlanByTaskIdModel {
    string userId = 1;
    string taskId = 2;
}