syntax = "proto3";

option csharp_namespace = "WorkflowService.Protos";

package WorkflowTaskSvc;

service WorkflowTaskSvc {
    rpc CreateTask (CreateWorkflowTaskModel) returns (CreateWorkflowTaskResponse);
    rpc GetTask (GetWorkflowTaskModel) returns (WorkflowTaskModel);
}

message CreateWorkflowTaskModel {
    string inputData = 1;
    string userId = 2;
}

message GetWorkflowTaskModel {
    string id = 1;
    string userId = 2;
}

message CreateWorkflowTaskResponse {
    string id = 1;
}

enum WorkflowTaskStatus {
    PENDING = 0;
    IN_PROGRESS = 1;
    COMPLETED = 2;
    FAILED = 3;
}

message WorkflowTaskModel {
    string id = 1;
    string userId = 2;
    string inputData = 3;
    WorkflowTaskStatus status = 4;
    string results = 5;
}